name: Flywheel SSH Deploy
on:
  push:
    tags:
      - 'staging/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v4.1.9
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ssh.getflywheel.com
          REMOTE_USER: ${{ secrets.STAGING_REMOTE_USER }}
          ARGS: -rltgoDzvO --exclude .git --exclude .github --exclude node_modules
          TARGET: /www/wp-content/themes/${{ github.event.repository.name }}
